### ISSUE TITLE
I can't add this extension in my collection on addons.mozilla.org

### ISSUE THREAD

**Issue by ghost** [M-Reimer/android-pdf-js#18]
Hi,
(Sorry if I miss some Github protocol, that's my first message ever wrote in github.)

I use exclusively Firefox Nightly on Android, last version.

I don't have any problem adding others extensions to my collection in addons.mozilla.org.

I've done it many many times and I'll describe it to you so you can check thats not a mistake from my part :

I go to "see my collections" then "Edit my collection" and below there's a search field where I can type the extension I want.

Then a list of extensions appears and I select the one I want. And then I go in the Nightly browser, in Addon manager section and I activate it.

The issue here is your extension "Android pdf.js" never appears when I write it in the appropriate search field. Others extension with pdf in it appears but not yours.
I've tried writing it other ways: just "PDF", just "android", or just "pdf.js".

Just for you know, the extension appears correctly in the addons.mozilla.org website if I look for it with the "at-the-top" main search field.

Is this a problem with my setup, or happening with anyone else ?
Could I install your extension by any other mean ?

Thanks for you great work.

**Comment by M-Reimer** [comment]
For your first Issue your description is surprisingly accurate.

I didn't know that people try to add Add-ons that way. And you are right: It won't work. The reason is, that addons.mozilla.org has "two modes". If you enter it from your desktop PC, then you'll only see Add-ons for the desktop version of Firefox. And on Android their search is basically completely broken as all they find are the ten or so Add-ons on Mozilla's whitelist.

To add the Add-on, you have to do it directly from the Add-on page on AMO. The link can be found on the README.md of this repo. It is: https://addons.mozilla.org/en-US/android/addon/android-pdf-js/ Look at the left side of the page to find an option to add it to your collection.

There is not much I can do about this. The whole situation on Android is really, really bad. But Mozilla wants it that way. Seems like they want to prevent getting too much market share by all cost. The way how they handle Add-ons is a big pile of :ox: :hankey:

**Comment by ghost** [comment]
Wow, you taught me a much better way to add something to my collection. 

I was always tearing my hairs out with my way of doing it : you're not the only extension that wasnt appearing in this search field, it happened with some others too, so I always ended renouncing adding them.

So after installation, I directly tried with a pdf link and it worked
perfectly !

You're a genius mate.

Thanks again
